simple_mail:
  sender_name: "Server"
  sender_icon: "default"
  ttl_days: 15

storage:
  type: sqlite
  sqlite:
    file: data.db
  mysql:
    host: localhost
    port: 3306
    database: mail_system
    username: root
    password: ""
    pool_size: 10
