name: MailSystem
version: '${version}'
main: org.ReDiego0.mailSystem.MailSystem
api-version: '1.21'
softdepend: [PlaceholderAPI, LuckPerms]

commands:
  mail:
    description: Open mail inbox or send mail
    usage: /mail [send|sendcomplex|purge] [args]
    permission: mailsystem.command.mail

permissions:
  mailsystem.command.mail:
    description: Open mail inbox
    default: true
  mailsystem.command.send:
    description: Send simple mail to players
    default: op
  mailsystem.command.sendcomplex:
    description: Send complex mail to players
    default: op
  mailsystem.command.purge:
    description: Purge all mails from a player
    default: op
